---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-operator-crds
  namespace: helm-base
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator-crds
  namespace: helm-base
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus-operator-crds
      version: '21.0.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-operator-crds
        namespace: helm-base
      interval: 24h
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-operator-crds-values
