version: 2.1
commands: # a reusable command with parameters
  greeting:
    parameters:
      name:
        default: "world"
        type: string
      surname:
        type: string
    steps:
      - run: echo "Hello << parameters.name >> << parameters.surname >>"
jobs:
  my-job:
    docker:
      - image: cimg/base:stable
    steps:
      - greeting:
          name: "Ankit"
          surname: "Sambhare"
workflows:
  my-workflow:
    jobs:
      - my-job
