# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  pr-comment:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Install jq for JSON parsing"
          command: sudo apt-get update && sudo apt-get install -y jq
      - run:
          name: "Debug environment variables"
          command: |
            echo "CIRCLE_PR_NUMBER: $CIRCLE_PR_NUMBER"
            echo "CIRCLE_PULL_REQUEST: $CIRCLE_PULL_REQUEST"
            echo "CIRCLE_PROJECT_USERNAME: $CIRCLE_PROJECT_USERNAME"
            echo "CIRCLE_PROJECT_REPONAME: $CIRCLE_PROJECT_REPONAME"
            echo "CIRCLE_BRANCH: $CIRCLE_BRANCH"
      - run:
          name: "Post comment on PR"
          command: |
            # Use the available environment variables
            REPO_OWNER="$CIRCLE_PROJECT_USERNAME"
            REPO_NAME="$CIRCLE_PROJECT_REPONAME"
            BRANCH_NAME="$CIRCLE_BRANCH"
            
            echo "Repository: $REPO_OWNER/$REPO_NAME"
            echo "Branch: $BRANCH_NAME"
            
            # Find PR using GitHub API and branch name
            echo "Looking for PR with head branch: $REPO_OWNER:$BRANCH_NAME"
            PR_RESPONSE=$(curl -s -H "Authorization: token $GH_TOKEN" \
              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls?head=$REPO_OWNER:$BRANCH_NAME&state=open")
            
            echo "API Response: $PR_RESPONSE"
            
            PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.[0].number // empty')
            
            if [ -n "$PR_NUMBER" ] && [ "$PR_NUMBER" != "null" ] && [ "$PR_NUMBER" != "" ]; then
              echo "Found PR #$PR_NUMBER for branch $BRANCH_NAME"

              PR_STATE = $(echo "$PR_RESPONSE" | jq -r  '.[0].state // empty')
              echo "State for the PR is: $PR_STATE"

              if [ $PR_STATE == "open" ]; then         
                # Post the comment
                echo "Posting comment to PR #$PR_NUMBER"
              
                HTTP_CODE=$(curl -s -o /tmp/response.json -w "%{http_code}" -X POST \
                  -H "Authorization: token $GH_TOKEN" \
                  -H "Accept: application/vnd.github.v3+json" \
                  -H "Content-Type: application/json" \
                  -d '{"body": "Good PR! 👍"}' \
                  "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/$PR_NUMBER/comments")
              
                echo "HTTP Response Code: $HTTP_CODE"
                echo "Response Body:"
                cat /tmp/response.json
              
                if [ "$HTTP_CODE" -eq 201 ]; then
                  echo "✅ Successfully posted comment to PR #$PR_NUMBER"
                else
                  echo "❌ Failed to post comment. HTTP Code: $HTTP_CODE"
                  exit 1
                fi
              else
                echo "❌ No open PR found for branch $BRANCH_NAME"
                echo "This might not be a PR build, or the PR might be closed/merged"
                exit 0
              fi
            fi

workflows:
  pr-workflow:
    jobs:
      - pr-comment:
          context: ctx-ci
          filters:
            branches:
              ignore: 
                - main
                - master
