version: 2.1

jobs:
  pr-comment:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Dump env vars for debugging"
          command: env | sort
      - run:
          name: "Post comment on PR"
          command: |
            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
              echo "This is a PR build: $CIRCLE_PULL_REQUEST"
            else
              echo "Not a pull request build. Skipping comment."
            fi

workflows:
  my-workflows:
    jobs:
      - pr-comment
      contexts: ctx-ci
      
