version: 2.1
commands:
  greeting:
    parameters:
      to:
        default: "world"
        type: string
      surname:
        default: "sambhare"
        type: string
    steps:
      - run: echo "Hello << parameters.to >> << parameters.surname >>"
jobs:
  my-job:
    docker:
      - image: cimg/base:stable
    steps:
      - greeting:
          to: "Ankit"
          surname: "Sambhare ji"
workflows:
  my-workflow:
    jobs:
      - my-job
