version: 2.1

jobs:
  pr-message:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Notify PR opened or updated"
          command: |
            echo "Pull request detected: Running notification job."
            # Add any other commands you want here.

workflows:
  pr-workflow:
    jobs:
      - pr-message:
          filters:
            pull_requests:
              types:
                - opened
                - reopened
                - synchronize
