version: 2.1

jobs:
  pr-message:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Notify if this is a pull request"
          command: |
            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
              echo "Pull request detected: $CIRCLE_PULL_REQUEST"
            else
              echo "Not a pull request build, skipping notification."
            fi

workflows:
  pr-workflow:
    jobs:
      - pr-message
