version: 2.1
commands:
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run: echo "Hello << parameters.to >>"
jobs:
  my-job:
    docker:
      - image: cimg/base:stable
    steps:
      - greeting:
          to: "Ankit Sambhare"
workflows:
  my-workflow:
    jobs:
      - my-job
