# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  pr-comment:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Post comment on PR"
          command: |
            # Use the available environment variables
            REPO_OWNER="$CIRCLE_PROJECT_USERNAME"
            REPO_NAME="$CIRCLE_PROJECT_REPONAME"
            BRANCH_NAME="$CIRCLE_BRANCH"
            
            echo "Repository: $REPO_OWNER/$REPO_NAME"
            echo "Branch: $BRANCH_NAME"
            
            # Find PR using GitHub API and branch name
            echo "Looking for PR with head branch: $REPO_OWNER:$BRANCH_NAME"
            PR_RESPONSE=$(curl -s -H "Authorization: token $GH_TOKEN" \
              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls?head=$REPO_OWNER:$BRANCH_NAME&state=open")
            
            echo "API Response: $PR_RESPONSE"
            
            PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.[0].number // empty')
            
            if [ -n "$PR_NUMBER" ] && [ "$PR_NUMBER" != "null" ] && [ "$PR_NUMBER" != "" ]; then
              echo "Found PR #$PR_NUMBER for branch $BRANCH_NAME"
              echo "Posting simple comment to PR #$CIRCLE_PR_NUMBER"
              
              # Post comment to GitHub using API with simple message
              RESPONSE=$(curl -s -w "HTTP_CODE:%{http_code}" -X POST \
                -H "Authorization: token $GH_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Content-Type: application/json" \
                -d '{"body": "Good PR! 👍"}' \
                "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PR_REPONAME/issues/$CIRCLE_PR_NUMBER/comments")

workflows:
  pr-workflow:
    jobs:
      - pr-comment:
          context: ctx-ci
          filters:
            branches:
              ignore: main
              
