# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  pr-comment:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Post comment on PR"
          command: |
              echo "Posting simple comment to PR #$PR_NUMBER"
              
              # Post comment to GitHub using API with simple message
              RESPONSE=$(curl -s -w "HTTP_CODE:%{http_code}" -X POST \
                -H "Authorization: token $GH_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                -H "Content-Type: application/json" \
                -d '{"body": "Good PR! 👍"}' \
                "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PR_REPONAME/issues/$CIRCLE_PR_NUMBER/comments")

workflows:
  pr-workflow:
    jobs:
      - pr-comment:
          context: ctx-ci
          filters:
            branches:
              ignore: main
              
