version: 2.1

orbs:
  github-cli: circleci/github-cli@2.1.0

jobs:
  comment-on-pr:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - github-cli/setup  # automatically uses the GitHub App token
      - run:
          name: Comment on PR
          command: |
            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
              gh pr comment "$CIRCLE_PULL_REQUEST" --body "✅ Auto-comment from CircleCI using GitHub App."
            else
              echo "Not a PR build, skipping comment."
            fi

workflows:
  comment-workflow:
    jobs:
      - comment-on-pr
