---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cadvisor
  namespace: cadvisor
spec:
  interval: 24h
  url: https://ckotzbauer.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cadvisor
  namespace: cadvisor
spec:
  interval: 1m
  timeout: 1m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: uninstall
  chart:
    spec:
      chart: cadvisor
      version: "2.3.3"
      sourceRef:
        kind: HelmRepository
        name: cadvisor
        namespace: cadvisor
      interval: 24h
  valuesFrom:
    - kind: ConfigMap
      name: cadvisor-values
